version: '3.7'

networks:
  board-games-back:

services:
  board-games-back:
    container_name: board-games-back
    build: ./
    logging:
      driver: "json-file"
      options:
        max-size: 10m
    networks:
      - board-games-back
    ports:
      - "8080:8080"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 1m
      timeout: 10s
      retries: 1
      start_period: 60s
